ALTER TABLE public.claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.claim_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.claim_evidence_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.claim_status_log ENABLE ROW LEVEL SECURITY;